name: run-pipeline

on: 
  push:
  #schedule:
  #  - cron:  '0 4 * * *'

jobs:

  pipeline:
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    
      - name: Install dependencies
        run: |
          sudo apt-get install \
            zip \
            openssh-client \
            git \
            libsodium-dev \
            libcurl4-openssl-dev \
            libv8-dev \
            libzmq3-dev \
            libxml2-dev \
            libz-dev \
            libglpk40 \
            libmagick++-dev \
            pandoc
    
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-renv@v2
  
      - name: Run pipeline
        run: |
          Rscript run.R
        shell: bash
      
      - uses: stefanzweifel/git-auto-commit-action@v5